name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-numpy python3-pytest pybind11-dev xz-utils

      - name: Install Criterion
        run: |
          wget https://github.com/Snaipe/Criterion/releases/download/v2.4.0/criterion-2.4.0-linux-x86_64.tar.xz
          tar -Jxf criterion-2.4.0-linux-x86_64.tar.xz
          sudo cp -r criterion-2.4.0/* /usr/local/

      - name: Build module
        run: |
          make PROFILE=TEST
          make PROFILE=RELEASE

      - name: Test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make test
