name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-numpy python3-pytest pybind11-dev

      - name: Install Criterion
        run: |
          wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2
          tar -jxf criterion-v2.3.3-linux-x86_64.tar.bz2
          sudo cp -r criterion-v2.3.3/* /usr/local/

      - name: Build module
        run: make PROFILE=TEST

      - name: Test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make test PROFILE=TEST
