name: Build Website

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-numpy python3-pip pybind11-dev doxygen doxygen-latex
          sudo pip install pdoc

      - name: Build documentation
        run: website/build.sh

      - name: Prepare artifact
        run: tar -C website/ --exclude build.sh -hcf website.tar .

      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./website.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
